yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "@fullhuman/postcss-purgecss@*":
    dependencies:
      "postcss": "*"
  react-scripts@*:
    dependencies:
      eslint-plugin-prettier: "*"
  eslint-plugin-prettier@*:
    dependencies:
      prettier: "*"
  pino@*:
    dependencies:
      pino-pretty: "*"
  rollup@*:
    dependencies:
      rollup-plugin-uglify: "*"
