query GetDataTree($urls: [String!]!) {
  servers(urls: $urls) {
    url
    databases {
      name
      schemas {
        name
        tables {
          name
          columns {
            name
            type
            default
            isNullable
          }
          indices {
            columnNames
            name
            isUnique
            isPrimary
          }
          foreignKeys {
            foreignTableSchemaName
            foreignTableName
            name
            columnNames
            foreignColumnNames
          }
          constraints {
            schemaName
            tableName
            name
            type
            columnNames
          }
          triggers {
            triggerSchema
            name
            events
            activation
            condition
            definition
          }
        }
        views {
          name
          columns {
            name
            type
            isNullable
          }
        }
        procedures {
          schemaName
          name
          returnSet
          returnType
          kind
          isTrigger
          argTypes
          argModes
          argNames
        }
      }
    }
  }
}
