query QueryFieldsAndRows($url: String!, $query: String!) {
  executeQuery(url: $url, query: $query) {
    fields {
      name
      type
    }
    rows
  }
}

query QueryRows($url: String!, $query: String!) {
  executeQuery(url: $url, query: $query) {
    rows
  }
}
